#!/bin/sh
# Renders testing/STATUS.md from test-plan.yaml and clauses.yaml.
#
# Everything here is computed. Blocked is never typed: a test needing a
# capability marked `available: no` renders as blocked with that reason, so the
# plan cannot claim a test is due when the world cannot produce it.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
ruby -ryaml -e '
  plan    = YAML.load_file(ARGV[0])
  all_clauses = YAML.load_file(ARGV[1])["clauses"]
  # Retired items keep their ids so history stays readable, and are counted
  # nowhere: a withdrawn requirement is not a gap.
  retired_clauses = all_clauses.select { |c| c["status"] == "deprecated" }
  clauses = all_clauses - retired_clauses
  caps    = plan["capabilities"]
  all_tests = plan["tests"]
  retired_tests = all_tests.select { |t| t["status"] == "deprecated" }
  tests = all_tests - retired_tests

  blocked_by = lambda { |t| (t["needs"] || []).select { |n| caps[n] && caps[n]["available"] == "no" } }

  done    = tests.select { |t| t["status"] == "successful" }
  failed  = tests.select { |t| t["status"] == "failed" }
  pending = tests.select { |t| t["status"] == "not done" }
  blocked = pending.select { |t| !blocked_by.call(t).empty? }
  due     = pending - blocked

  # A clause is verified only when every test citing it is successful.
  by_clause = Hash.new { |h, k| h[k] = [] }
  tests.each { |t| (t["verifies"] || []).each { |v| by_clause[v] << t } }
  verified = clauses.count { |c| ts = by_clause[c["id"]]; !ts.empty? && ts.all? { |t| t["status"] == "successful" } }

  out = []
  out << "# Test status"
  out << ""
  out << "Generated by `testing/report.sh` from `test-plan.yaml` and `clauses.yaml`. Do not edit."
  out << ""
  out << "| | count |"
  out << "|---|---|"
  out << "| FSD clauses inventoried | #{clauses.size} |"
  out << "| Clauses fully verified | #{verified} |"
  out << "| Tests declared | #{tests.size} |"
  out << "| successful | #{done.size} |"
  out << "| failed | #{failed.size} |"
  out << "| due (runnable now) | #{due.size} |"
  out << "| blocked (capability unavailable) | #{blocked.size} |"
  out << ""
  out << "A clause counts as verified only when every test citing it is successful. Most are not, and that is information rather than failure."
  out << ""

  unless failed.empty?
    out << "## Failed"
    out << ""
    failed.each { |t| out << "- **#{t["id"]}** — #{t["title"]}" }
    out << ""
  end

  out << "## Done, with outcome"
  out << ""
  out << "| Test | Tier | Outcome | Evidence |"
  out << "|---|---|---|---|"
  done.sort_by { |t| [t["tier"], t["id"]] }.each do |t|
    out << "| `#{t["id"]}` #{t["title"]} | #{t["tier"]} | #{t["evidence"] || "passing"}#{t["last_run"] ? " (#{t["last_run"]})" : ""} | #{t["implemented_by"] || "-"} |"
  end
  out << ""
  gaps = done.select { |t| t["not_covered"] }
  unless gaps.empty?
    out << "**What these passes do not cover**"
    out << ""
    gaps.each { |t| out << "- `#{t["id"]}`: #{t["not_covered"]}" }
    out << ""
  end

  out << "## Due now — nothing is stopping these"
  out << ""
  out << "| Test | Tier | Needs | Why it has not run |"
  out << "|---|---|---|---|"
  due.sort_by { |t| [t["tier"], t["id"]] }.each do |t|
    out << "| `#{t["id"]}` #{t["title"]} | #{t["tier"]} | #{(t["needs"] || []).join(", ")} | #{t["reason"]} |"
  end
  out << ""

  out << "## Blocked — the world cannot produce the precondition yet"
  out << ""
  out << "| Test | Tier | Blocked on | How that precondition is created |"
  out << "|---|---|---|---|"
  blocked.sort_by { |t| [t["tier"], t["id"]] }.each do |t|
    miss = blocked_by.call(t)
    how = miss.map { |m| caps[m]["how"] }.join("; ")
    out << "| `#{t["id"]}` #{t["title"]} | #{t["tier"]} | #{miss.join(", ")} | #{how} |"
  end
  out << ""

  unless retired_clauses.empty? && retired_tests.empty?
    out << "## Retired"
    out << ""
    out << "Withdrawn requirements and the tests that carried them. Ids are kept so they are never reused, and counted nowhere above."
    out << ""
    retired_clauses.each { |c| out << "- `#{c["id"]}` #{c["text"]} — #{c["note"]}" }
    retired_tests.each { |t| out << "- `#{t["id"]}` #{t["title"]} — #{t["reason"]}" }
    out << ""
  end

  out << "## Capabilities"
  out << ""
  out << "| Capability | Available | What it is | How it is created |"
  out << "|---|---|---|---|"
  caps.each do |name, c|
    out << "| `#{name}` | #{c["available"]} | #{c["what"]} | #{c["how"]} |"
  end
  out << ""
  lim = caps.select { |_, c| c["limits"] }
  unless lim.empty?
    out << "**Rig limitations, with their consequence**"
    out << ""
    lim.each { |name, c| out << "- `#{name}`: #{c["limits"]}" }
    out << ""
  end

  out << "## Coverage by area"
  out << ""
  out << "| Area | Tests | successful | due | blocked |"
  out << "|---|---|---|---|---|"
  tests.group_by { |t| t["area"] }.sort.each do |area, ts|
    d = ts.count { |t| t["status"] == "successful" }
    b = ts.count { |t| t["status"] == "not done" && !blocked_by.call(t).empty? }
    out << "| #{area} | #{ts.size} | #{d} | #{ts.size - d - b} | #{b} |"
  end
  out << ""

  out << "## Clauses with no successful test"
  out << ""
  out << "Grouped by the section they come from, so a gap points at a chapter rather than a list."
  out << ""
  unver = clauses.reject { |c| ts = by_clause[c["id"]]; !ts.empty? && ts.all? { |t| t["status"] == "successful" } }
  unver.group_by { |c| c["source_section"] }.sort.each do |sec, cs|
    out << "- **#{sec}** (#{cs.size}): #{cs.map { |c| "`#{c["id"]}`" }.join(", ")}"
  end
  out << ""

  File.write(ARGV[2], out.join("\n") + "\n")
  puts "STATUS.md written: #{tests.size} tests, #{done.size} successful, #{due.size} due, #{blocked.size} blocked, #{verified}/#{clauses.size} clauses verified"
' "$here/test-plan.yaml" "$here/clauses.yaml" "$here/STATUS.md"
